#!/bin/bash
DIR=`dirname $0`
gradle7 clean
rm  $DIR/src/main/java/aar226_akc55_ayc62_ahl88/EtaLexer.java
jflex $DIR/src/main/java/aar226_akc55_ayc62_ahl88/etalex.flex
gradle7 --no-daemon -b build.gradle shadowJar