#!/bin/bash
DIR=`dirname $0`

exts=("lexed" "parsed" "typed" "ir" "s" "dot")

for ext in ${exts[@]}
do
  find $DIR -name "*.${ext}" -exec rm -r {} \;
done

pushd $DIR/src/main/java/aar226_akc55_ayc62_ahl88
rm EtaLexer.java Lexer.java EtaLexer.java~ Lexer.java~
rm EtaParser.java EtiParser.java parser.java sym.java
popd

rm  -r $DIR/build