
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package aar226_akc55_ayc62_ahl88;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNDERSCORE = 42;
  public static final int LENGTH = 16;
  public static final int LT = 24;
  public static final int CLOSE_BRACKET = 34;
  public static final int INTEGER_LITERAL = 5;
  public static final int error = 1;
  public static final int INT = 8;
  public static final int MINUS = 18;
  public static final int DIVIDE = 21;
  public static final int RETURN = 14;
  public static final int OPEN_BRACE = 37;
  public static final int CLOSE_BRACE = 38;
  public static final int SEMICOLON = 41;
  public static final int BREAK = 13;
  public static final int ELSE = 11;
  public static final int IDENTIFIER = 2;
  public static final int EOF = 0;
  public static final int IF = 10;
  public static final int HI_MULT = 20;
  public static final int COMMA = 40;
  public static final int OR = 29;
  public static final int TIMES = 19;
  public static final int CHARACTER_LITERAL = 4;
  public static final int USE = 15;
  public static final int EQUAL = 30;
  public static final int MODULO = 22;
  public static final int OPEN_BRACKET = 33;
  public static final int TRUE = 6;
  public static final int COLON = 39;
  public static final int GT = 26;
  public static final int UMINUS = 43;
  public static final int NOT = 23;
  public static final int GEQ = 27;
  public static final int OPEN_PAREN = 35;
  public static final int BOOL = 9;
  public static final int AND = 28;
  public static final int NOT_EQUAL = 31;
  public static final int LEQ = 25;
  public static final int STRING_LITERAL = 3;
  public static final int FALSE = 7;
  public static final int WHILE = 12;
  public static final int CLOSE_PAREN = 36;
  public static final int GETS = 32;
  public static final int PLUS = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "STRING_LITERAL",
  "CHARACTER_LITERAL",
  "INTEGER_LITERAL",
  "TRUE",
  "FALSE",
  "INT",
  "BOOL",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "RETURN",
  "USE",
  "LENGTH",
  "PLUS",
  "MINUS",
  "TIMES",
  "HI_MULT",
  "DIVIDE",
  "MODULO",
  "NOT",
  "LT",
  "LEQ",
  "GT",
  "GEQ",
  "AND",
  "OR",
  "EQUAL",
  "NOT_EQUAL",
  "GETS",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "COLON",
  "COMMA",
  "SEMICOLON",
  "UNDERSCORE",
  "UMINUS"
  };
}

