package aar226_akc55_ayc62_ahl88.asm.Opts;

public enum WorkListEnum {
    PRECOLORED,
    INITIAL,
    SIMPLIFYWORKLIST,
    FREEZEWORKLIST,
    SPILLWORKLIST,
    SPILLEDNODES,
    COALESCEDNODES,
    COLOREDNODES,
    SELECTSTACK
}
